update pgstores for blog tables

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -25,22 +25,67 @@ tasks:
 
         FOUND_DB=false
         for dbuser in "${USERS[@]}"; do
-            COMMAND="psql -U $dbuser -d $DBNAME -c '\\conninfo'"
-            echo "Attempt: $COMMAND"
-            eval $COMMAND &> /dev/null
-            if [ $? -eq 0 ]; then
-                USER=$dbuser
-                FOUND_DB=true
-                break
-            fi
+          COMMAND="psql -U $dbuser -d $DBNAME -c '\\conninfo'"
+          echo "Attempt: $COMMAND"
+          # Use command substitution to capture error
+          ERROR=$(eval "$COMMAND" 2>&1 >/dev/null)
+            
+          # $? stores exit value of the last command
+          if [ $? -eq 0 ]; then
+            USER=$dbuser
+            FOUND_DB=true
+            break
+          else
+            echo "Failure for user: ${dbuser}"
+            echo "Error: $ERROR"
+          fi
         done 
 
         if [ "$FOUND_DB" = true ]; then
-            psql -U ${USER} -d ${DBNAME} -c "${USE_EXISTING_USER_COMMAND}"
-            psql -U ${USER} -d ${DBNAME} -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '${TARGET_DB}' AND pid <> pg_backend_pid();"
-            psql -U ${USER} -d ${DBNAME} -c "DROP DATABASE IF EXISTS ${TARGET_DB};"
-            psql -U ${USER} -d ${DBNAME} -c "CREATE DATABASE ${TARGET_DB};"
-            psql -U ${USER} -d ${DBNAME} -c "ALTER DATABASE ${TARGET_DB} OWNER TO ${TARGET_USER};"
+            COMMAND="psql -U ${USER} -d ${DBNAME} -c \"${USE_EXISTING_USER_COMMAND}\""
+            echo "Executing: $COMMAND"
+            ERROR=$(eval "$COMMAND" 2>&1)
+            if [ $? -ne 0 ]; then
+              echo "Failed to execute command: $COMMAND"
+              echo "Error: $ERROR"
+              exit 1
+            fi
+
+            COMMAND="psql -U ${USER} -d ${DBNAME} -c \"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '${TARGET_DB}' AND pid <> pg_backend_pid();\""
+            echo "Executing: $COMMAND"
+            ERROR=$(eval "$COMMAND" 2>&1)
+            if [ $? -ne 0 ]; then
+              echo "Failed to execute command: $COMMAND"
+              echo "Error: $ERROR"
+              exit 1
+            fi
+
+            COMMAND="psql -U ${USER} -d ${DBNAME} -c \"DROP DATABASE IF EXISTS ${TARGET_DB};\""
+            echo "Executing: $COMMAND"
+            ERROR=$(eval "$COMMAND" 2>&1)
+            if [ $? -ne 0 ]; then
+              echo "Failed to execute command: $COMMAND"
+              echo "Error: $ERROR"
+              exit 1
+            fi
+
+            COMMAND="psql -U ${USER} -d ${DBNAME} -c \"CREATE DATABASE ${TARGET_DB};\""
+            echo "Executing: $COMMAND"
+            ERROR=$(eval "$COMMAND" 2>&1)
+            if [ $? -ne 0 ]; then
+              echo "Failed to execute command: $COMMAND"
+              echo "Error: $ERROR"
+              exit 1
+            fi
+
+            COMMAND="psql -U ${USER} -d ${DBNAME} -c \"ALTER DATABASE ${TARGET_DB} OWNER TO ${TARGET_USER};\""
+            echo "Executing: $COMMAND"
+            ERROR=$(eval "$COMMAND" 2>&1)
+            if [ $? -ne 0 ]; then
+              echo "Failed to execute command: $COMMAND"
+              echo "Error: $ERROR"
+              exit 1
+            fi
         else
             echo "Could not establish connection to the DB"
             exit 1
